spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
  security:
  oauth2:
    client:
    registration:
      facebook:
        clientId: <facebook client id>
        clientSecret: <facebook client secret>
        scope: <email, public_profile>








